export const scr = 'scr'
export const comp = 'comp'
export const style = 'style'
export const reducer = 'reducer'
export const reducerAction = 'reducer_action'
export const reducerTypes = 'reducer_types'
export const reducerSagas = 'reducer_sagas'
